# -----------------------------------------------------------------------------
# Reproduction Script (LLM Evaluation Context Only)
#
# This script reproduces internal LLM evaluation benchmarks and reporting
# pipelines used within the WFGY repository.
#
# It does NOT reproduce physical experiments, scientific laboratory tests,
# or externally validated empirical results.
#
# All outputs generated by this script are limited to:
# - Model evaluation runs
# - Synthetic benchmark suites
# - HTML reporting artifacts
#
# The term "reproduction" here refers strictly to software-level execution
# consistency within the repository environment.
# -----------------------------------------------------------------------------

# reproduce.sh

#!/usr/bin/env bash
set -euo pipefail

python verify_manifest.py
pip install -e .
wfgy init
wfgy evaluate --suite all
wfgy evaluate --suite efficiency
wfgy report --format html --output wfgy_results/report.html

echo "SUCCESS: reproduction complete."

